# Conteúdo correto para mkdocs.yml

site_name: DocEasyTek
site_url: https://rgustavo32.github.io/docEasyTek/
theme:
  name: material

nav:
  - 'Início': 'index.md'
  - 'Lista de Pendências': 'pendence_list.md'
  - 'Guia para Analise - Tensionadora': 'estudo_software.md'
  - 'Manutenção e Deploy':
      - 'Fluxo de Trabalho (Resumo )': 'manutencao_e_deploy/00_fluxo_resumido.md'  # <-- NOVA PÁGINA AQUI
      - 'Implantação Inicial': 'manutencao_e_deploy/01_implantacao_inicial.md'
      - 'Ciclo de Vida da Atualização':
          - 'Fase 1: Preparação': 'manutencao_e_deploy/ciclo_de_vida_atualizacao/01_preparacao.md'
          - 'Fase 2: Desenvolvimento Local': 'manutencao_e_deploy/ciclo_de_vida_atualizacao/02_desenvolvimento_local.md'
          - 'Fase 3: Validação em Dev': 'manutencao_e_deploy/ciclo_de_vida_atualizacao/03_validacao_em_dev.md'
          - 'Fase 4: Merge e Oficialização': 'manutencao_e_deploy/ciclo_de_vida_atualizacao/04_merge_e_oficializacao.md'
          - 'Fase 5: Deploy em Produção': 'manutencao_e_deploy/ciclo_de_vida_atualizacao/05_deploy_em_producao.md'
      - 'Reset do Ambiente': 'manutencao_e_deploy/03_reset_completo_do_ambiente.md'
      - 'Subir e Descer Aplicação': 'manutencao_e_deploy/04_Comandos.md'
